//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSMantisConnect.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VSMantisConnect {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VSMantisConnect() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSMantisConnect.Resources.VSMantisConnect", typeof(VSMantisConnect).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create tool window.
        /// </summary>
        internal static string ErrCannotShowToolWindow {
            get {
                return ResourceManager.GetString("ErrCannotShowToolWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, configure extension before use.
        /// </summary>
        internal static string ErrExtensionNotConfigured {
            get {
                return ResourceManager.GetString("ErrExtensionNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading view.
        /// </summary>
        internal static string MantisConnectWindowErrorLoadingView {
            get {
                return ResourceManager.GetString("MantisConnectWindowErrorLoadingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension loaded.
        /// </summary>
        internal static string MantisConnectWindowLoaded {
            get {
                return ResourceManager.GetString("MantisConnectWindowLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading view....
        /// </summary>
        internal static string MantisConnectWindowLoadingView {
            get {
                return ResourceManager.GetString("MantisConnectWindowLoadingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing {0} view....
        /// </summary>
        internal static string MantisConnectWindowViewInitializing {
            get {
                return ResourceManager.GetString("MantisConnectWindowViewInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View {0} loaded.
        /// </summary>
        internal static string MantisConnectWindowViewLoaded {
            get {
                return ResourceManager.GetString("MantisConnectWindowViewLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SettingsViewbtnSave {
            get {
                return ResourceManager.GetString("SettingsViewbtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string SettingsViewbtnTest {
            get {
                return ResourceManager.GetString("SettingsViewbtnTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize end point.
        /// </summary>
        internal static string SettingsViewckbCustomizeEndPoint {
            get {
                return ResourceManager.GetString("SettingsViewckbCustomizeEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save password.
        /// </summary>
        internal static string SettingsViewckbSavePassword {
            get {
                return ResourceManager.GetString("SettingsViewckbSavePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsViewDisplayName {
            get {
                return ResourceManager.GetString("SettingsViewDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading settings failed.
        /// </summary>
        internal static string SettingsViewErrorLoading {
            get {
                return ResourceManager.GetString("SettingsViewErrorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantis base url.
        /// </summary>
        internal static string SettingsViewlblBaseUrl {
            get {
                return ResourceManager.GetString("SettingsViewlblBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End point.
        /// </summary>
        internal static string SettingsViewlblEndpoint {
            get {
                return ResourceManager.GetString("SettingsViewlblEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingsViewlblLanguage {
            get {
                return ResourceManager.GetString("SettingsViewlblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SettingsViewlblPassword {
            get {
                return ResourceManager.GetString("SettingsViewlblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string SettingsViewlblUsername {
            get {
                return ResourceManager.GetString("SettingsViewlblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings loaded.
        /// </summary>
        internal static string SettingsViewLoaded {
            get {
                return ResourceManager.GetString("SettingsViewLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Settings....
        /// </summary>
        internal static string SettingsViewLoading {
            get {
                return ResourceManager.GetString("SettingsViewLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings changed. Don&apos;t forget to save.
        /// </summary>
        internal static string SettingsViewSettingsChanged {
            get {
                return ResourceManager.GetString("SettingsViewSettingsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved.
        /// </summary>
        internal static string SettingsViewSettingsSaved {
            get {
                return ResourceManager.GetString("SettingsViewSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing connection....
        /// </summary>
        internal static string SettingsViewTestingConnection {
            get {
                return ResourceManager.GetString("SettingsViewTestingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        internal static string SettingsViewTestingFailed {
            get {
                return ResourceManager.GetString("SettingsViewTestingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to Mantis. Reason : {0}.
        /// </summary>
        internal static string SettingsViewTestingFailedMessage {
            get {
                return ResourceManager.GetString("SettingsViewTestingFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection success..
        /// </summary>
        internal static string SettingsViewTestingSuccess {
            get {
                return ResourceManager.GetString("SettingsViewTestingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} successfully connected.
        /// </summary>
        internal static string SettingsViewTestingSuccessMessage {
            get {
                return ResourceManager.GetString("SettingsViewTestingSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
    }
}
